name: Gokko SDK

on:
  push:
    branches:
    tags:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Prepare GCP Credentials
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" >> ./gekko.json

      - name: Run Tests
        env:
          GCP_PROJECT_ID: agekkoå
          SERVICE_NAME: gokko-sdk
        run: make citest

      - name: Send coverage to CodeClimate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/coverage/.coverage:gocov
          prefix: github.com/agekko/gokko-sdk